# Global
global.button.ok=Ok
global.button.cancel=Cancel
global.dialog.error=Error
global.dialog.message=Message
global.button.close=Close
global.button.close_other=Close Other
global.button.close_all=Close All

# matrixeater/src/com/ysera
# matrixeater/src/com/ysera.Menu
ysera.app.title=Ysera War3 Model Editor Pre-Alpha .01
ysera.menu.file=File
ysera.menu.recent_files=Recent Files
ysera.menu.edit=Edit
ysera.menu.view=View
ysera.menu.team_color=Team Color
ysera.menu.windows=Windows
ysera.menu.extras=Extras
ysera.menu.help=Help

# matrixeater/src/com/matrixeater/MainPanel
matrixeater.menu.file=File
matrixeater.menu.edit=Edit
matrixeater.menu.open_recent=Open Recent
matrixeater.menu.open_recent_description=Allows you to access recently opened files.
matrixeater.menu.file_description=Allows the user to open, save, close, and manipulate files.
matrixeater.menu.tools=Tools
matrixeater.menu.reset_layout=Reset Layout
matrixeater.menu.views=Views
matrixeater.menu.team_color=Team Color
matrixeater.menu.test=test
matrixeater.menu.animation_preview=Animation Preview
matrixeater.menu.animation_controller=Animation Controller
matrixeater.menu.camera_controller=Camera Controller
matrixeater.menu.modeling=Modeling
matrixeater.menu.tools_description=Tools and utilities
matrixeater.menu.view=View
matrixeater.menu.view_description=Allows the user to control view settings.
matrixeater.menu.team_color_description=Allows the user to control team color settings.
matrixeater.menu.window=Window
matrixeater.menu.window_description=Allows the user to open various windows containing the program features.
matrixeater.menu.about=Help
matrixeater.menu.clear=Clear
matrixeater.menuitem.changelog=Changelog
matrixeater.menuitem.about=About
matrixeater.menu.language=Language
matrixeater.menuitem.language.en=English
matrixeater.menuitem.language.zh_CN=简体中文
matrixeater.menu.outliner=Outliner
matrixeater.menu.perspective=Perspective
matrixeater.menu.front=Front
matrixeater.menu.side=Side
matrixeater.menu.bottom=Bottom
matrixeater.menu.tools_item=Tools
matrixeater.menu.footer=Footer
matrixeater.menu.tracks=Tracks
matrixeater.menu.contents=Contents
matrixeater.menu.component=Component
matrixeater.menu.text=Text
matrixeater.menu.matrix_eater_script=Matrix Eater Script
matrixeater.menu.export_animated_frame_png=Export Animated Frame PNG
matrixeater.menuitem.oinkerwinkle_animtransfer=Oinkerwinkle-Style AnimTransfer
matrixeater.menu.browsers=Browsers
matrixeater.menuitem.data_browser=Data Browser
matrixeater.menuitem.unit_browser=Unit Browser
matrixeater.menuitem.doodad_browser=Doodad Browser
matrixeater.menuitem.hive_browser=Hive Browser
matrixeater.menu.add=Add
matrixeater.menuitem.add=Allows the user to add new components to the model.
matrixeater.menu.particle=Particle

matrixeater.stockFiles.no_parent=No parent
matrixeater.stockFiles.parent=Parent:
matrixeater.stockFiles.add=Add
matrixeater.stockFiles.particle_name=Particle Name:

matrixeater.println.rigAction=NOT RIGGING, NOT VALID

matrixeater.button.chooseanimations=Choose when to show!
matrixeater.button.color=Color 
matrixeater.button.visibility=Visibility

matrixeater.menuitem.merge_geoset=Oinkerwinkle-Style Merge Geoset

matrixeater.calculate_extents.prompt=This will calculate the extents of all model components. Proceed?
matrixeater.calculate_extents.warning=(It may destroy existing extents)
matrixeater.calculate.button.all_geosets=Consider all geosets for calculation
matrixeater.calculate.button.current_geosets=Consider current editable geosets for calculation

matrixeater.action.nothing_to_redo=Nothing to redo!
matrixeater.action.nothing_to_undo=Nothing to undo!
matrixeater.button.refresh=Refresh
matrixeater.button.apply=Apply
matrixeater.button.find_f3=Find (F3)
matrixeater.button.animate=Animate

matrixeater.title.edit=Edit
matrixeater.title.view=View
matrixeater.title.model=Model

matrixeater.tab.view_unit_browser=Unit Browser
matrixeater.tab.view_data_browser=Data Browser

matrixeater.toobar.new=New
matrixeater.toobar.open=Open
matrixeater.toobar.save=Save
matrixeater.toobar.undo=Undo
matrixeater.toobar.redo=Redo
matrixeater.toobar.select_and_move=Select and Move
matrixeater.toobar.select_and_rotate=Select and Rotate
matrixeater.toobar.select_and_scale=Select and Scale
matrixeater.toobar.select_and_extrude=Select and Extrude
matrixeater.toobar.select_and_extend=Select and Extend
matrixeater.toobar.snap=Snap

matrixeater.tooltip.create_keyframe=Create Keyframe
matrixeater.tooltip.choose_time_bounds=Choose Time Bounds
matrixeater.tooltip.change_game_directory=Changes the directory from which to load texture files for the 3D display.

matrixeater.dialog.error.file_type_unknown=File type unknown or unavailable
matrixeater.dialog.error.no_file_type_specified=No file type was specified
matrixeater.dialog.error.no_output_file_specified=No output file was specified
matrixeater.dialog.error.no_import_file_specified=No import file was specified
matrixeater.dialog.change_language=Change Language
matrixeater.dialog.change_language_text=Restart immediately to take effect?
matrixeater.dialog.color_chooser=Color Chooser
matrixeater.dialog.openpreferencesaction=Preferences
matrixeater.dialog.openmodelfile=Please open a model file.
matrixeater.dialog.settime=Set Time Bounds

matrixeater.window.openUnitViewerAction=Unit Browser
matrixeater.window.openDoodadViewerAction=MPQ Browser
matrixeater.view.openDoodadViewerAction=Doodad Browser
matrixeater.label.openHiveViewerAction=Resource Type
matrixeater.comboBox.openHiveViewerAction=Any
matrixeater.border.openHiveViewerAction_resource=Resource Filters
matrixeater.view.openHiveViewerAction_bo=Bongo Bongo (Phantom Shadow Beast)
matrixeater.view.openHiveViewerAction_other=Other Model
matrixeater.border.openHiveViewerAction_tags=Tags
matrixeater.checkbox.openhivevieweraction_results=Results must include all selected tags
matrixeater.label.openHiveViewerAction_types=Types (Models)
matrixeater.checkbox.openhivevieweraction_build=Building
matrixeater.checkbox.openhivevieweraction_doodad=Doodad
matrixeater.checkbox.openhivevieweraction_item=Item
matrixeater.checkbox.openhivevieweraction_ui=User Interface
matrixeater.view.openHiveViewerAction_hive=Hive Browser
matrixeater.view.viewportcontrollerwindowviewport=Outliner
matrixeater.view.toolview=Tools
matrixeater.view.modeldataview=Contents
matrixeater.view.tracks=Tracks
matrixeater.view.component=Component
matrixeater.view.windowundocking=: (windowUndocking removedWindow as view) title bar visible now
matrixeater.view.windowremoved_barproperties=: (removedWindow as view) title bar visible now
matrixeater.view.windowremoved_singlechildview=: (singleChildView, windowRemoved()) title bar visible now
matrixeater.view.windowremoved_force=: force close because 0 child windows in windowRemoved()
matrixeater.view.windowclosing_barproperties=: (closingWindow as view) title bar visible now
matrixeater.view.windowclosing_singlechildview=: (singleChildView, windowClosing()) title bar visible now
matrixeater.view.windowclosing_force=: force close because 0 child windows in windowClosing()
matrixeater.view.windowadd=: (singleChildView as view, windowAdded()) title bar NOT visible now
matrixeater.view.barproperties=: (addedWindow as view) title bar NOT visible now
matrixeater.view.side=Side
matrixeater.view.front=Front
matrixeater.view.bottom=Bottom
matrixeater.view.perspective=Perspective
matrixeater.view.preview=Preview
matrixeater.view.footer=Footer
matrixeater.view.run=Run
matrixeater.view.text=Text
matrixeater.view.modeling=Modeling
matrixeater.view.animation_controller=Animation Controller
matrixeater.view.camera_controller=Camera Controller

matrixeater.dialog.actionperformed=Must open a file!
matrixeater.dialog.export_texture=Export Texture
matrixeater.dialog.image_file= Image File
matrixeater.dialog.addtoolbar_choose=Choose settings:
matrixeater.dialog.addtoolbar_tp_settings=T-Pose Settings

matrixeater.status.done=Done!

matrixeater.message.bad_choice_no_animation=Bad choice. No animation added.
matrixeater.message.no_visibility_will_be_copied=No visibility will be copied.
matrixeater.message.added_animation_prefix=Added dialog.not_implemented=Not yet implemented for this application.

# matrixeater/src/com/matrixeater/AnimationFrame
matrixeater.animationframe.title=Animation Editor:

matrixeater.animation_transfer_done=Animation transfer done!

# matrixeater/src/com/matrixeater/AnimationPanel
matrixeater.animationpanel.global_sequence=Global Sequence 

# matrixeater/src/com/matrixeater/ClonedNodeNamePickerImplementation
matrixeater.clonednodename.copy= copy
matrixeater.clonednodename.enter_name=Enter name for clone of \"
matrixeater.clonednodename.choose_node_name=Choose Node Names

# Status messages
status.loading=Loading...
status.collapsing_mdl_representation=Collapsing MatrixEater MDL representation
status.preparing_model_editing=Preparing model for editing...
status.adding_stand_animation=Adding "Stand" animation...
status.scanning_wow_sizing=Scanning for WoW sizing...
status.scanning_convertable_textures=Scanning for convertable textures...
status.converting_textures=Converting textures...
status.saving_file=Saving file...

# Dialogs
dialog.wow_scaling.title=WoW Scaling
dialog.wow_scaling.message=This model might be a WoW model, or peculiarly small. Would you like to increase its size?
option.scale_x32=x32
option.scale_x64=x64
option.scale_x128=x128
option.no=No

dialog.convert_textures.title=Convert Textures to BLPs
dialog.convert_textures.message=This OBJ model contains references to non-BLP files in its materials. Automatically create corresponding BLP files? If you choose YES, the MDL format of this OBJ will also be generated to support Matrix Eater 3D viewing.

# Labels
label.parent=Parent:
label.add=Add
label.particle_name=Particle Name:
label.x=X:
label.y=Y:
label.z=Z:
label.textures=Textures
label.image_viewer=Image Viewer
label.display_path=Display Path

# Dialogs
message.calculate_extents.prompt=This will calculate the extents of all model components. Proceed?
message.calculate_extents.warning=(It may destroy existing extents)
dialog.confirm.title=Message
dialog.add_texture.title=Add Texture
dialog.add_texture.message=Enter texture path:
dialog.error.title=Error
dialog.error.please_open_model_file=Please open a model file.

# Buttons
button.import=Import
button.export=Export
button.replace_texture=Replace Texture
button.remove=Remove
button.edit_path=Edit Path
button.add_path=Add Path

# Errors
error.unable_convert_png=Unable to convert PNG to BLP.
error.casting_shadows_not_supported=Casting shadows not supported in WC3

# Status
status.converting_group=Converting %s ...
dialog.error.must_open_file=Must open a file!
dialog.error.chosen_model_could_not_be_used=The chosen model could not be used.
dialog.error.program=Program Error
menu.close=Close
menu.close_others=Close Others
menu.close_all=Close All
menu.browsers=Browsers
menu.data_browser=Data Browser
menu.unit_browser=Unit Browser
menu.doodad_browser=Doodad Browser
menu.hive_browser=Hive Browser
menu.add=Add
menu.particle=Particle
button.choose_when_to_show=Choose when to show!
menu.single=Single
menu.from_file=From File
menu.from_unit=From Unit
menu.from_model=From Model
menu.from_object=From Object
menu.export_animated_to_static_mesh=Export Animated to Static Mesh
dialog.error.must_be_in_animation_editor=You must be in the Animation Editor to use that!

menu.import=Import
menu.import_from_file=From File
menu.import_from_unit=From Unit
menu.import_from_wc3_model=From WC3 Model
menu.import_from_object_editor=From Object Editor
menu.import_from_workspace=From Workspace
menu.save=Save
menu.save_as=Save as
menu.export_texture=Export Texture
menu.revert=Revert
menu.exit=Exit
menu.optimize=Optimize
menu.linearize_animations=Linearize Animations
menu.simplify_keyframes=Simplify Keyframes (Experimental)
menu.minimize_geosets=Minimize Geosets
menu.cut=Cut
menu.copy=Copy
menu.paste=Paste
menu.duplicate=Duplicate
menu.snap_vertices=Snap Vertices
menu.snap_normals=Snap Normals
menu.select_all=Select All
menu.invert_selection=Invert Selection
menu.expand_selection=Expand Selection
menu.delete=Delete
button.transfer=Transfer
button.done=Done
button.go_advanced=Go Advanced
button.ok=OK
button.cancel=Cancel
button.load_file=Load File
button.save_file=Save File

dialog.error.no_file_type_specified=No file type was specified
button.browse=Browse
button.generate=Generate