package com.hiveworkshop.rms.ui.browsers.jworldedit.objects.datamodel;

public class WE_STRING {
	public static String WESTRING_AEVAL_LVL = "WESTRING_AEVAL_LVL";
	public static String WESTRING_DEVAL_VAR = "WESTRING_DEVAL_VAR";
	public static String WESTRING_ERROR_BADTRIGVAL = "WESTRING_ERROR_BADTRIGVAL";

	public static String WESTRING_OE_TYPECAT_SUFFIX_AREAEFFECT = "WESTRING_OE_TYPECAT_SUFFIX_AREAEFFECT";
	public static String WESTRING_OE_TYPECAT_SUFFIX_CASTER = "WESTRING_OE_TYPECAT_SUFFIX_CASTER";
	public static String WESTRING_OE_TYPECAT_SUFFIX_EFFECT = "WESTRING_OE_TYPECAT_SUFFIX_EFFECT";
	public static String WESTRING_OE_TYPECAT_SUFFIX_MISSILE ="WESTRING_OE_TYPECAT_SUFFIX_MISSILE";
	public static String WESTRING_OE_TYPECAT_SUFFIX_SPECIAL = "WESTRING_OE_TYPECAT_SUFFIX_SPECIAL";
	public static String WESTRING_OE_TYPECAT_SUFFIX_TARGET = "WESTRING_OE_TYPECAT_SUFFIX_TARGET";
	public static String WESTRING_OE_TYPECAT_UNIT = "WESTRING_OE_TYPECAT_UNIT";
	public static String WESTRING_OE_TYPECAT_UNIT_MSSL = "WESTRING_OE_TYPECAT_UNIT_MSSL";
	public static String WESTRING_OE_TYPECAT_UNIT_SPEC = "WESTRING_OE_TYPECAT_UNIT_SPEC";
	public static String WESTRING_OE_TYPECAT_ITEM = "WESTRING_OE_TYPECAT_ITEM";
	public static String WESTRING_OE_TYPECAT_ABIL = "WESTRING_OE_TYPECAT_ABIL";
	public static String WESTRING_OE_TYPECAT_BUFF = "WESTRING_OE_TYPECAT_BUFF";
	public static String WESTRING_OE_TYPECAT_DEST = "WESTRING_OE_TYPECAT_DEST";
	public static String WESTRING_OE_TYPECAT_DOOD = "WESTRING_OE_TYPECAT_DOOD";
	public static String WESTRING_OE_TYPECAT_SPWN = "WESTRING_OE_TYPECAT_SPWN";
	public static String WESTRING_OE_TYPECAT_SKIN = "WESTRING_OE_TYPECAT_SKIN";
	public static String WESTRING_OE_TYPECAT_XTRA = "WESTRING_OE_TYPECAT_XTRA";
	public static String WESTRING_PREVIEWER_VAR = "WESTRING_PREVIEWER_VAR";
	public static String WESTRING_UNITCOLOR_ = "WESTRING_UNITCOLOR_";
	public static String WESTRING_TOOLBAR_NEW = "WESTRING_TOOLBAR_NEW";
	public static String WESTRING_TOOLBAR_OPEN = "WESTRING_TOOLBAR_OPEN";
	public static String WESTRING_TOOLBAR_SAVE = "WESTRING_TOOLBAR_SAVE";
	public static String WESTRING_MENU_OE_UNIT_COPY = "WESTRING_MENU_OE_UNIT_COPY";
	public static String WESTRING_MENU_OE_UNIT_PASTE = "WESTRING_MENU_OE_UNIT_PASTE";
	public static String WESTRING_TOOLBAR_SE_NEWCAT = "WESTRING_TOOLBAR_SE_NEWCAT";
	public static String WESTRING_TOOLBAR_SE_NEWTRIG = "WESTRING_TOOLBAR_SE_NEWTRIG";
	public static String WESTRING_TOOLBAR_SE_NEWTRIGCOM = "WESTRING_TOOLBAR_SE_NEWTRIGCOM";
	public static String WESTRING_MENU_MODULE_TERRAIN = "WESTRING_MENU_MODULE_TERRAIN";
	public static String WESTRING_MENU_MODULE_SCRIPTS = "WESTRING_MENU_MODULE_SCRIPTS";
	public static String WESTRING_MENU_MODULE_SOUND = "WESTRING_MENU_MODULE_SOUND";
	public static String WESTRING_MENU_OBJECTEDITOR = "WESTRING_MENU_OBJECTEDITOR";
	public static String WESTRING_MENU_MODULE_CAMPAIGN = "WESTRING_MENU_MODULE_CAMPAIGN";
	public static String WESTRING_MENU_MODULE_AI = "WESTRING_MENU_MODULE_AI";
	public static String WESTRING_MENU_OBJECTMANAGER = "WESTRING_MENU_OBJECTMANAGER";
	public static String WESTRING_MENU_IMPORTMANAGER = "WESTRING_MENU_IMPORTMANAGER";
	public static String WESTRING_TOOLBAR_TESTMAP = "WESTRING_TOOLBAR_TESTMAP";
	public static String WESTRING_UNTITLEDTRIGGER = "WESTRING_UNTITLEDTRIGGER";
	public static String WESTRING_TRIGGERCOMMENT_DEFAULT = "WESTRING_TRIGGERCOMMENT_DEFAULT";
	public static String WESTRING_UNTITLEDTRIGGERCATEGORY = "WESTRING_UNTITLEDTRIGGERCATEGORY";
	public static String WESTRING_OBJTAB_UNITS = "WESTRING_OBJTAB_UNITS";
	public static String WESTRING_OBJTAB_ITEMS = "WESTRING_OBJTAB_ITEMS";
	public static String WESTRING_OBJTAB_DESTRUCTABLES = "WESTRING_OBJTAB_DESTRUCTABLES";
	public static String WESTRING_OBJTAB_DOODADS = "WESTRING_OBJTAB_DOODADS";
	public static String WESTRING_OBJTAB_ABILITIES = "WESTRING_OBJTAB_ABILITIES";
	public static String WESTRING_OBJTAB_BUFFS = "WESTRING_OBJTAB_BUFFS";
	public static String WESTRING_OBJTAB_UPGRADES = "WESTRING_OBJTAB_UPGRADES";

}
