name: Package via Gradle

on:
  push:
    tags: ['CN']
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create full distribution
        run: ./gradlew.bat clean :matrixeater:installDist --no-daemon

      - name: Archive distribution
        uses: actions/upload-artifact@v4
        with:
          name: retera-jwc3-windows-portable
          path: D:/a/ReterasModelStudio/ReterasModelStudio